name: Deploy Pages
on:
push:
branches: [ "main" ]
permissions:
contents: read
pages: write
id-token: write
concurrency:
group: "pages"
cancel-in-progress: true
jobs:
deploy:
environment:
name: github-pages
url: ${{ steps.deployment.outputs.page_url }}
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Upload site
uses: actions/upload-pages-artifact@v4
with:
path: ./BACK/Public
- name: Deploy to Pages
id: deployment
uses: actions/deploy-pages@v4
